name: build and deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Build & Push Frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./easychat-frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/easychat-frontend:latest

        # Build & Push Backend
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./easychat-backend/docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/easychat-backend:latest